
name: Coverity4openssl

#Run on push
on:
  push:
    branches:
      - master
#Run once a day
#on:
#  schedule:
#    - cron:  '20 0 * * *'

jobs:
  coverity:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: config
      run: |
        date 
        CC=gcc ./config --banner=Configured --debug enable-fips enable-rc5 enable-md2 enable-ssl3 enable-nextprotoneg enable-ssl3-method enable-weak-ssl-ciphers enable-zlib enable-ec_nistp_64_gcc_128 no-shared enable-buildtest-c++ enable-external-tests -DPEDANTIC -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION
        ./configdata.pm --dump
    - name: tool download
      run: |
        time wget https://scan.coverity.com/download/linux64 \
             --post-data "token=${{ secrets.COVERITY_TOKEN_OPENSSL }}&project=${{ secrets.COVERITY_PROJECT_NAME }}" \
             --progress=dot:giga -O coverity_tool.tgz
    - name: tool install
      run: |
        ls -alh coverity_tool.tgz
        time tar xzf coverity_tool.tgz
    - name: make
      run: time ./cov-analysis*/bin/cov-build --dir cov-int make -j2 || true
    - name: archive
      run: |
        time tar czvf ${{ secrets.COVERITY_PROJECT_NAME }}.tgz cov-int
        ls -alh *.tgz   
    - name: Coverity upload
      run: |
        curl --form token="${{ secrets.COVERITY_TOKEN_OPENSSL }}" \
             --form email="${{ secrets.COVERITY_EMAIL_ADDR }}" \
             --form file=@${{ secrets.COVERITY_PROJECT_NAME }}.tgz \
             --form version="$(date -u -I)-$(git rev-parse --short HEAD)" \
             --form description="analysis of $(git branch --show-current)" \
             https://scan.coverity.com/builds?project=${{ secrets.COVERITY_PROJECT_NAME }}
